[build]
  command = "node build.mjs"
  publish = "dist"

# Deploy Previews and branch deploys use the same build
[context.deploy-preview]
  command = "node build.mjs"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
